<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8ujw2ay\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8ujw2ay/appProdProjectContainer.php') {
    touch(__DIR__.'/Container8ujw2ay.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container8ujw2ay\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container8ujw2ay\appProdProjectContainer([
    'container.build_hash' => '8ujw2ay',
    'container.build_id' => '2c104fd5',
    'container.build_time' => 1701642991,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8ujw2ay');
